//! Unix service management for KixDNS
//!
//! Supports:
//! - systemd (most modern Linux distributions)
//! - OpenRC (Gentoo, Alpine Linux)
//! - Procd (OpenWrt)
//! - BSD rc.d (FreeBSD)
//!
//! Unix 服务管理：支持 systemd、OpenRC、Procd 和 BSD rc.d。

use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::Context;
use tokio::sync::oneshot;
use tracing::info;

use crate::service::InitSystem;
use crate::service::detect_init_system;

// ============================================================================
// Service file templates
// ============================================================================

/// Generate a systemd service unit.
///
/// Output: `/etc/systemd/system/kixdns.service`
fn systemd_unit(exe: &Path, config: &Path, listener_label: &str) -> String {
    format!(
        r#"# KixDNS systemd service unit
# Auto-generated by kixdns service install — do not edit manually.
#
# Install:  kixdns service install
# Uninstall: kixdns service uninstall
# Start:    systemctl start kixdns
# Enable:   systemctl enable kixdns

[Unit]
Description=KixDNS DNS Server
Documentation=https://github.com/kixdns/kixdns
After=network.target
Wants=nss-lookup.target

[Service]
Type=simple
ExecStart={exe} run \
    --config {config} \
    --listener-label {label}
Restart=on-failure
RestartSec=5
User=nobody
Group=nogroup
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
LimitNOFILE=65536
PrivateTmp=true
ProtectSystem=full
ProtectHome=true

[Install]
WantedBy=multi-user.target
"#,
        exe = exe.display(),
        config = config.display(),
        label = listener_label,
    )
}

/// Generate an OpenRC init script.
///
/// Output: `/etc/init.d/kixdns`
fn openrc_script(exe: &Path, config: &Path, listener_label: &str) -> String {
    format!(
        r#"#!/sbin/openrc-run
# KixDNS OpenRC init script
# Auto-generated by kixdns service install — do not edit manually.
#
# Install:   kixdns service install
# Uninstall: kixdns service uninstall
# Start:     rc-service kixdns start
#           or: /etc/init.d/kixdns start

name="KixDNS DNS Server"
description="High-performance async DNS server with hot-reloadable pipeline configuration"
command="{exe}"
command_args="run --config {config} --listener-label {label}"
command_user="nobody:nogroup"
pidfile="/run/${{RC_SVCNAME}}.pid"
command_background=false

depend() {{
    need net
    use dns logger
}}
"#,
        exe = exe.display(),
        config = config.display(),
        label = listener_label,
    )
}

/// Generate a Procd init script (OpenWrt).
///
/// Output: `/etc/init.d/kixdns`
fn procd_script(exe: &Path, config: &Path, listener_label: &str) -> String {
    format!(
        r#"#!/bin/sh /etc/rc.common
# KixDNS Procd init script (OpenWrt)
# Auto-generated by kixdns service install — do not edit manually.
#
# Install:   kixdns service install
# Uninstall: kixdns service uninstall
# Start:     /etc/init.d/kixdns start
# Enable:    /etc/init.d/kixdns enable

USE_PROCD=1

start_service() {{
    procd_open_instance
    procd_set_param command "{exe}"
    procd_append_param command run --config {config} --listener-label {label}
    procd_set_param user nobody
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}}

stop_service() {{
    # The service will be stopped automatically by procd
    :
}}

service_triggers() {{
    procd_add_reload_trigger "kixdns"
}}
"#,
        exe = exe.display(),
        config = config.display(),
        label = listener_label,
    )
}

/// Generate a FreeBSD rc.d script.
///
/// Output: `/usr/local/etc/rc.d/kixdns`
fn bsd_rc_script(exe: &Path, config: &Path, listener_label: &str) -> String {
    format!(
        r#"#!/bin/sh
#
# PROVIDE: kixdns
# REQUIRE: NETWORKING SERVERS
# KEYWORD: shutdown
#
# Auto-generated by kixdns service install — do not edit manually.
#
# Install:   kixdns service install
# Uninstall: kixdns service uninstall
# Start:     service kixdns start
# Enable:    echo 'kixdns_enable="YES"' >> /etc/rc.conf

. /etc/rc.subr

name="kixdns"
rcvar="kixdns_enable"

load_rc_config $name

: ${{kixdns_enable:="NO"}}
: ${{kixdns_config:="{config}"}}
: ${{kixdns_listener_label:="{label}"}}
: ${{kixdns_user:="nobody"}}

command="{exe}"
command_args="run --config ${{kixdns_config}} --listener-label ${{kixdns_listener_label}}"
command_user="${{kixdns_user}}"
pidfile="/var/run/kixdns.pid"

run_rc_command "$1"
"#,
        exe = exe.display(),
        config = config.display(),
        label = listener_label,
    )
}

// ============================================================================
// Service file installation paths
// ============================================================================

fn systemd_path() -> PathBuf {
    PathBuf::from("/etc/systemd/system/kixdns.service")
}

fn openrc_path() -> PathBuf {
    PathBuf::from("/etc/init.d/kixdns")
}

fn procd_path() -> PathBuf {
    PathBuf::from("/etc/init.d/kixdns")
}

fn bsd_rc_path() -> PathBuf {
    PathBuf::from("/usr/local/etc/rc.d/kixdns")
}

// ============================================================================
// Install logic
// ============================================================================

/// Install KixDNS as a system service on Unix.
///
/// Auto-detects the init system and installs the appropriate service file.
pub fn install_service(config: &PathBuf, listener_label: &str) -> anyhow::Result<()> {
    let init = detect_init_system();
    let exe = std::env::current_exe().context("failed to get current executable path")?;

    println!("→ Detected init system: {}", init.description());

    match init {
        InitSystem::Systemd => install_systemd(&exe, config, listener_label),
        InitSystem::OpenRc => install_openrc(&exe, config, listener_label),
        InitSystem::Procd => install_procd(&exe, config, listener_label),
        InitSystem::BsdRc => install_bsd_rc(&exe, config, listener_label),
        InitSystem::Unknown | _ => {
            anyhow::bail!(
                "Could not auto-detect init system.\n\
                 ┌─ Please create a service script manually ──────────────────────┐\n\
                 │                                                                  │\n\
                 │  systemd:  Write a .service unit to /etc/systemd/system/         │\n\
                 │  OpenRC:   Write an init script to /etc/init.d/                  │\n\
                 │  Procd:    Write a procd script to /etc/init.d/                  │\n\
                 │  FreeBSD:  Write a rc.d script to /usr/local/etc/rc.d/           │\n\
                 │                                                                  │\n\
                 │  The binary is at: {}  │\n\
                 │  Run it with: {} run --config {}      │\n\
                 │                                                                  │\n\
                 └──────────────────────────────────────────────────────────────┘\n\
                 ",
                exe.display(),
                exe.display(),
                config.display(),
            )
        }
    }
}

fn install_systemd(exe: &Path, config: &Path, listener_label: &str) -> anyhow::Result<()> {
    let path = systemd_path();
    let content = systemd_unit(exe, config, listener_label);

    write_service_file(&path, &content, 0o644)?;

    // Reload systemd, enable and start
    run_command("systemctl", &["daemon-reload"])?;
    run_command("systemctl", &["enable", "kixdns"])?;
    run_command("systemctl", &["start", "kixdns"])?;

    println!("✓ KixDNS installed as a systemd service.");
    println!("  Unit file : {}", path.display());
    println!("  Status    : systemctl status kixdns");
    println!("  Logs      : journalctl -u kixdns -f");
    Ok(())
}

fn install_openrc(exe: &Path, config: &Path, listener_label: &str) -> anyhow::Result<()> {
    let path = openrc_path();
    let content = openrc_script(exe, config, listener_label);

    write_service_file(&path, &content, 0o755)?;

    run_command("rc-update", &["add", "kixdns", "default"])?;
    run_command("rc-service", &["kixdns", "start"])?;

    println!("✓ KixDNS installed as an OpenRC service.");
    println!("  Init script : {}", path.display());
    println!("  Status      : rc-service kixdns status");
    Ok(())
}

fn install_procd(exe: &Path, config: &Path, listener_label: &str) -> anyhow::Result<()> {
    let path = procd_path();
    let content = procd_script(exe, config, listener_label);

    write_service_file(&path, &content, 0o755)?;

    run_command("/etc/init.d/kixdns", &["enable"])?;
    run_command("/etc/init.d/kixdns", &["start"])?;

    println!("✓ KixDNS installed as a Procd service (OpenWrt).");
    println!("  Init script : {}", path.display());
    println!("  Status      : /etc/init.d/kixdns status");
    Ok(())
}

fn install_bsd_rc(exe: &Path, config: &Path, listener_label: &str) -> anyhow::Result<()> {
    let path = bsd_rc_path();
    let content = bsd_rc_script(exe, config, listener_label);

    write_service_file(&path, &content, 0o755)?;

    println!("✓ KixDNS installed as a FreeBSD rc.d service.");
    println!("  Script     : {}", path.display());
    println!("  Enable     : echo 'kixdns_enable=\"YES\"' >> /etc/rc.conf");
    println!("  Start      : service kixdns start");
    println!(
        "  Config     : Add 'kixdns_config=\"{}\"' to /etc/rc.conf for custom path",
        config.display()
    );
    Ok(())
}

// ============================================================================
// Uninstall logic
// ============================================================================

/// Uninstall KixDNS system service on Unix.
pub fn uninstall_service() -> anyhow::Result<()> {
    let init = detect_init_system();

    println!("→ Detected init system: {}", init.description());

    match init {
        InitSystem::Systemd => uninstall_systemd(),
        InitSystem::OpenRc => uninstall_openrc(),
        InitSystem::Procd => uninstall_procd(),
        InitSystem::BsdRc => uninstall_bsd_rc(),
        InitSystem::Unknown | _ => {
            anyhow::bail!(
                "Could not auto-detect init system.\n\
                 Please manually remove the service file you created earlier."
            );
        }
    }
}

fn uninstall_systemd() -> anyhow::Result<()> {
    let path = systemd_path();

    // Stop and disable
    let _ = run_command("systemctl", &["stop", "kixdns"]);
    let _ = run_command("systemctl", &["disable", "kixdns"]);

    // Remove unit file
    if path.exists() {
        std::fs::remove_file(&path).context("failed to remove systemd unit file")?;
    }
    let _ = run_command("systemctl", &["daemon-reload"]);

    println!("✓ KixDNS systemd service uninstalled.");
    Ok(())
}

fn uninstall_openrc() -> anyhow::Result<()> {
    let path = openrc_path();

    let _ = run_command("rc-service", &["kixdns", "stop"]);
    let _ = run_command("rc-update", &["delete", "kixdns"]);

    if path.exists() {
        std::fs::remove_file(&path).context("failed to remove OpenRC init script")?;
    }

    println!("✓ KixDNS OpenRC service uninstalled.");
    Ok(())
}

fn uninstall_procd() -> anyhow::Result<()> {
    let path = procd_path();

    if path.exists() {
        let _ = run_command("/etc/init.d/kixdns", &["stop"]);
        let _ = run_command("/etc/init.d/kixdns", &["disable"]);
        std::fs::remove_file(&path).context("failed to remove Procd init script")?;
    }

    println!("✓ KixDNS Procd service uninstalled.");
    Ok(())
}

fn uninstall_bsd_rc() -> anyhow::Result<()> {
    let path = bsd_rc_path();

    let _ = run_command("service", &["kixdns", "stop"]);

    if path.exists() {
        std::fs::remove_file(&path).context("failed to remove BSD rc.d script")?;
    }

    println!("✓ KixDNS BSD rc.d service uninstalled.");
    println!("  Note: You may want to remove 'kixdns_enable=\"YES\"' from /etc/rc.conf manually.");
    Ok(())
}

// ============================================================================
// Run as service (Unix)
// ============================================================================

/// Run the DNS server with signal-based graceful shutdown.
///
/// Sets up handlers for SIGTERM, SIGINT, and SIGQUIT to trigger
/// a graceful shutdown of the server.
pub fn run_service(config: PathBuf, listener_label: String) -> anyhow::Result<()> {
    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .context("failed to build tokio runtime for service")?;

    rt.block_on(async move {
        let (shutdown_tx, shutdown_rx) = oneshot::channel::<()>();

        // Set up signal handlers inside the tokio runtime
        // 在 tokio 运行时内设置信号处理
        tokio::spawn(async move {
            wait_for_signal_async().await;
            let _ = shutdown_tx.send(());
        });

        crate::run_dns_server_with_shutdown(config, listener_label, shutdown_rx).await
    })?;

    info!("Service stopped gracefully");
    Ok(())
}

/// Wait for a termination signal using tokio's signal module.
/// Listens for SIGTERM, SIGINT, and SIGQUIT.
pub async fn wait_for_signal_async() {
    use tokio::signal::unix::{SignalKind, signal};

    let mut term = signal(SignalKind::terminate()).expect("failed to create SIGTERM listener");
    let mut int = signal(SignalKind::interrupt()).expect("failed to create SIGINT listener");
    let mut quit = signal(SignalKind::quit()).expect("failed to create SIGQUIT listener");

    tokio::select! {
        _ = term.recv() => info!("Received SIGTERM"),
        _ = int.recv() => info!("Received SIGINT"),
        _ = quit.recv() => info!("Received SIGQUIT"),
    }
}

// ============================================================================
// Helpers
// ============================================================================

/// Write a service file to disk, creating parent directories if needed.
fn write_service_file(path: &Path, content: &str, mode: u32) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create directory: {}", parent.display()))?;
    }

    let mut file = std::fs::File::create(path)
        .with_context(|| format!("failed to create service file: {}", path.display()))?;

    file.write_all(content.as_bytes())
        .with_context(|| format!("failed to write service file: {}", path.display()))?;

    // Set file permissions
    use std::os::unix::fs::PermissionsExt;
    file.set_permissions(std::fs::Permissions::from_mode(mode))
        .with_context(|| format!("failed to set permissions on: {}", path.display()))?;

    Ok(())
}

/// Run a shell command and return its exit status.
fn run_command(program: &str, args: &[&str]) -> anyhow::Result<()> {
    let output = std::process::Command::new(program)
        .args(args)
        .output()
        .with_context(|| format!("failed to execute: {} {}", program, args.join(" ")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!(
            "Command failed ({} {}): {}",
            program,
            args.join(" "),
            stderr.trim()
        );
    }

    Ok(())
}
