//! Windows Service Control Manager (SCM) integration for KixDNS
//!
//! Windows SCM 集成：安装、卸载、运行 Windows 服务。

use std::ffi::OsString;
use std::path::PathBuf;
use std::sync::OnceLock;
use std::time::Duration;

use anyhow::Context;
use tokio::sync::oneshot;
use tracing::info;

use windows_service::{
    define_windows_service,
    service::{
        ServiceAccess, ServiceControl, ServiceControlAccept, ServiceDependency,
        ServiceErrorControl, ServiceExitCode, ServiceInfo, ServiceStartType, ServiceState,
        ServiceStatus, ServiceType,
    },
    service_control_handler::{self, ServiceControlHandlerResult},
    service_dispatcher,
    service_manager::{ServiceManager, ServiceManagerAccess},
};

/// Service name registered with the SCM / 在 SCM 中注册的服务名称
pub const SERVICE_NAME: &str = "KixDNS";

/// Display name shown in Services.msc / 在服务管理器中显示的名称
pub const SERVICE_DISPLAY_NAME: &str = "KixDNS DNS Server";

/// Service description / 服务描述
pub const SERVICE_DESCRIPTION: &str =
    "High-performance async DNS server with hot-reloadable pipeline configuration.";

/// Global configuration: (config_path, listener_label)
/// Set before dispatching the service, read inside the service main function.
static SERVICE_CONFIG: OnceLock<(PathBuf, String)> = OnceLock::new();

// ---------------------------------------------------------------------------
// FFI service entry point — generated by the macro
// ---------------------------------------------------------------------------
define_windows_service!(ffi_service_main, my_service_main);

/// The actual service main function called by the SCM on a background thread.
fn my_service_main(_arguments: Vec<OsString>) {
    // Init tracing inside the service context
    let _ = tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .try_init();

    let (config, listener_label) = match SERVICE_CONFIG.get() {
        Some(cfg) => cfg.clone(),
        None => {
            tracing::error!("SERVICE_CONFIG not set; using defaults");
            (PathBuf::from("config/pipeline.json"), "default".to_string())
        }
    };

    if let Err(e) = run_service(config, listener_label) {
        tracing::error!("Service exited with error: {:#}", e);
    }
}

/// Run the DNS server as a Windows service with proper SCM integration.
fn run_service(config: PathBuf, listener_label: String) -> anyhow::Result<()> {
    // 1. Install the ring crypto provider (same as normal startup)
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("failed to install rustls crypto provider");

    // 2. Register service control event handler
    let (shutdown_tx, shutdown_rx) = oneshot::channel::<()>();
    let shutdown_tx = std::sync::Mutex::new(Some(shutdown_tx));

    let status_handle = service_control_handler::register(SERVICE_NAME, move |control_event| {
        match control_event {
            ServiceControl::Stop | ServiceControl::Shutdown => {
                info!("Service received stop/shutdown signal");
                if let Some(tx) = shutdown_tx.lock().unwrap().take() {
                    let _ = tx.send(());
                }
                ServiceControlHandlerResult::NoError
            }
            // Interrogate is mandatory — must respond NoError
            ServiceControl::Interrogate => ServiceControlHandlerResult::NoError,
            _ => ServiceControlHandlerResult::NotImplemented,
        }
    })?;

    // 3. Report SERVICE_RUNNING to SCM
    status_handle.set_service_status(ServiceStatus {
        service_type: ServiceType::OWN_PROCESS,
        current_state: ServiceState::Running,
        controls_accepted: ServiceControlAccept::STOP | ServiceControlAccept::SHUTDOWN,
        exit_code: ServiceExitCode::NO_ERROR,
        checkpoint: 0,
        wait_hint: Duration::default(),
        process_id: None,
    })?;

    info!(
        "Service is now running (config={:?}, listener_label={})",
        config, listener_label
    );

    // 4. Create tokio runtime and run the DNS server, passing the shutdown signal
    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .context("failed to build tokio runtime for service")?;

    rt.block_on(async {
        crate::run_dns_server_with_shutdown(config, listener_label, shutdown_rx).await
    })?;

    // 5. Report SERVICE_STOPPED
    status_handle.set_service_status(ServiceStatus {
        service_type: ServiceType::OWN_PROCESS,
        current_state: ServiceState::Stopped,
        controls_accepted: ServiceControlAccept::empty(),
        exit_code: ServiceExitCode::NO_ERROR,
        checkpoint: 0,
        wait_hint: Duration::default(),
        process_id: None,
    })?;

    info!("Service stopped gracefully");
    Ok(())
}

// ---------------------------------------------------------------------------
// Public API — called from mod.rs
// ---------------------------------------------------------------------------

/// Install KixDNS as a Windows service.
///
/// Registers the service with the SCM so that it can be started automatically
/// on boot or manually via `sc start` / Services.msc.
pub fn install_service(config: &PathBuf, listener_label: &str) -> anyhow::Result<()> {
    let manager = ServiceManager::local_computer(
        None::<&str>, // default database (active)
        ServiceManagerAccess::CONNECT | ServiceManagerAccess::CREATE_SERVICE,
    )
    .context("failed to open Service Control Manager (try running as Administrator)")?;

    let exe_path = std::env::current_exe().context("failed to get current executable path")?;

    // Build launch arguments: "service run --config <path> --listener-label <label>"
    let launch_arguments: Vec<OsString> = vec![
        OsString::from("service"),
        OsString::from("run"),
        OsString::from("--config"),
        OsString::from(config.as_os_str()),
        OsString::from("--listener-label"),
        OsString::from(listener_label),
    ];

    let service_info = ServiceInfo {
        name: OsString::from(SERVICE_NAME),
        display_name: OsString::from(SERVICE_DISPLAY_NAME),
        service_type: ServiceType::OWN_PROCESS,
        start_type: ServiceStartType::AutoStart,
        error_control: ServiceErrorControl::Normal,
        executable_path: exe_path.clone(),
        launch_arguments,
        dependencies: vec![
            ServiceDependency::Service(OsString::from("Tcpip")),
            ServiceDependency::Service(OsString::from("Dnscache")),
        ],
        account_name: None,     // LocalSystem
        account_password: None, // LocalSystem
    };

    let service = manager
        .create_service(
            &service_info,
            ServiceAccess::CHANGE_CONFIG | ServiceAccess::START | ServiceAccess::DELETE,
        )
        .context("failed to create service (try running as Administrator)")?;

    // Set friendly description
    service
        .set_description(SERVICE_DESCRIPTION)
        .context("failed to set service description")?;

    println!("✓ Service '{}' installed successfully.", SERVICE_NAME);
    println!("  Display name : {}", SERVICE_DISPLAY_NAME);
    println!("  Binary path  : {}", exe_path.display());
    println!("  Config       : {}", config.display());
    println!("  Status       : Use `sc start KixDNS` or Services.msc to start.");
    Ok(())
}

/// Uninstall KixDNS from the SCM database.
pub fn uninstall_service() -> anyhow::Result<()> {
    let manager = ServiceManager::local_computer(
        None::<&str>, // default database (active)
        ServiceManagerAccess::CONNECT,
    )
    .context("failed to open Service Control Manager (try running as Administrator)")?;

    let service = manager
        .open_service(
            SERVICE_NAME,
            ServiceAccess::DELETE | ServiceAccess::STOP | ServiceAccess::QUERY_STATUS,
        )
        .context("service 'KixDNS' not found or cannot be opened")?;

    // Try to stop the service if it's running
    let status = service
        .query_status()
        .context("failed to query service status")?;

    if status.current_state != ServiceState::Stopped {
        println!("→ Stopping service '{}'...", SERVICE_NAME);
        service.stop()?;
        // Wait briefly for the service to stop
        std::thread::sleep(Duration::from_secs(3));
    }

    // Mark for deletion
    service
        .delete()
        .context("failed to delete service (try running as Administrator)")?;

    println!("✓ Service '{}' uninstalled successfully.", SERVICE_NAME);
    Ok(())
}

/// Run the service dispatcher (blocks the main thread until the service stops).
///
/// Called from `main()` when the user executes `kixdns service run`.
pub fn run_service_dispatcher(config: PathBuf, listener_label: String) -> anyhow::Result<()> {
    SERVICE_CONFIG
        .set((config, listener_label))
        .map_err(|_| anyhow::anyhow!("SERVICE_CONFIG already set (concurrent dispatch?)"))?;

    service_dispatcher::start(SERVICE_NAME, ffi_service_main)
        .context("service dispatcher failed to start")?;

    Ok(())
}
